Count connects and disconnects

diff --git a/.github/workflows/enforce-labelling.yml b/.github/workflows/enforce-labelling.yml
--- a/.github/workflows/enforce-labelling.yml
+++ b/.github/workflows/enforce-labelling.yml
@@ -28,27 +28,31 @@ jobs:
           PR_NUMBER=$(jq -r '.pull_request.number' $GITHUB_EVENT_PATH)
           REPO_OWNER=$(jq -r '.repository.owner.login' $GITHUB_EVENT_PATH)
           REPO_NAME=$(jq -r '.repository.name' $GITHUB_EVENT_PATH)
+          TIMELINE_JSON=$(curl -s "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$PR_NUMBER/timeline")
 
-          TIMELINE_JSON=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$PR_NUMBER/timeline")
-          echo "Timeline JSON: $TIMELINE_JSON"
-
+          # Count the number of times the timeline sees a "connected" event and subract the number of "disconnected" events
           LINKED_ISSUES=$(echo "$TIMELINE_JSON" | jq '
             reduce .[] as $event (
-              {};
-              if ($event.event == "cross-referenced" or $event.event == "connected") and ($event.source.issue != null) then
-                .[$event.source.issue.number] = true
-              elif $event.event == "unlinked" and ($event.source.issue != null) then
-                del(.[$event.source.issue.number])
+              0;
+              if $event.event == "connected" then
+                . + 1
+              elif $event.event == "disconnected" then
+                . - 1
               else
                 .
               end
-            ) | keys | length')
+            )')
+
+          # If the sum is 0, then no linked issues were found
           if [ "$LINKED_ISSUES" -eq "0" ]; then
             echo "No linked issues found in the pull request."
             exit 1
+          elif [ "$LINKED_ISSUES" -lt "0" ]; then
+            echo "Error: More disconnected events than connected events. This shouldn't be possible and likely indicates a bi ol' 🪲"
+            exit 1
+          else
+            echo "Linked issues found: $LINKED_ISSUES"
           fi
-
   validate-issue:
     runs-on: ubuntu-latest
     steps:
